### ISSUE TITLE
Monitor container logs not in this stack?

### ISSUE THREAD

**Issue by MunumButt** [ruanbekker/docker-monitoring-stack-gpnc#23]
Hey

Just wondering if there is already the ability to monitor the logs of containers not in this docker-compose stack - i.e containers running on the same server but in a different compose stack

**Comment by fforootd** [comment]
I think you can just update the promtail config to scrape all containers by removing the filter.

```
scrape_configs:
  - job_name: flog_scrape 
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        # filters:
        #   - name: label
        #     values: ["logging=promtail"] 
```
